version: 2.1
orbs:
  node: circleci/node@3.0.0

jobs:
  build:
    docker:
      - image: circleci/<language>:<version TAG>
    steps:
      - checkout
      - run: echo "this is a test build job"

workflows:
  build-and-test:
    jobs:
      - build
      - node/test
