name: Build Android APK for PR

on:
  pull_request:
    branches:
      - master

jobs:	
  build:	
    name: Build Android APK
    runs-on: ubuntu-latest	
    steps:	
      - name: Checkout source	
        uses: actions/checkout@v2	

      - name: Setup java	
        uses: actions/setup-java@v1	
        with:	
          java-version: 1.8	

      - name: Setup Node.js	
        uses: actions/setup-node@v1	
        with:	
          node-version: 13.x	

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Install Capacitor
        run: npm install -g @capacitor/core @capacitor/cli

      - name: Install Ionic	
        run: npm install -g @ionic/cli	

      - name: Install app dependencies	
        run: npm install	

      - name: Build app	
        run: ionic capacitor sync android

      - name: Grant execute permission for gradlew
        working-directory: ./android/
        run: chmod +x gradlew

      - name: Generate the Android APK	
        working-directory: ./android/
        run: ./gradlew --no-daemon assembleDebug --info

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v1	
        with:	
          name: hymnal-app-debug
          path: android/app/build/outputs/apk/debug/app-debug.apk
          
      - name: Add Comment on PR
        uses: mshick/add-pr-comment@v1
        with:
          message: Android APK for this PR has been built and uploaded. Check Github Actions.
          repo-token: ${{ secrets.GITHUB_TOKEN }}
