name: Build Android	

on:
  push:
    branches:
      - master

jobs:	
  build:	
    name: Build APK	
    runs-on: ubuntu-latest	
    steps:	
      - name: Checkout source	
        uses: actions/checkout@v2	

      - name: Setup java	
        uses: actions/setup-java@v1	
        with:	
          java-version: 1.8	

      - name: Setup Node.js	
        uses: actions/setup-node@v1	
        with:	
          node-version: 13.x	

      - name: Install Android SDK
        run: sudo apt update && sudo apt install android-sdk

      - name: Install Capacitor
        run: npm install -g @capacitor/core @capacitor/cli

      - name: Install Ionic	
        run: npm install -g @ionic/cli	

      - name: Install app dependencies	
        run: npm install	

      - name: Build Android APK	
        run: ionic capacitor sync android

      - name: Generate the Android App Bundle	
        working-directory: ./android/
        run: ./gradlew build

      - name: Upload APK	
        uses: actions/upload-artifact@v1	
        with:	
          name: hymnal-app
          path: android/app/build/outputs/apk/debug/app-debug.apk	
