name: Build and Test

on:
  pull_request:
    branches:
      - master


jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 13.x

      - name: Install Capacitor
        run: npm install -g @capacitor/core @capacitor/cli

      - name: Install Ionic
        run: npm install -g @ionic/cli

      - name: Install app dependencies
        run: npm install

      - name: Build
        run: npm build

      - name: Test
        run: npm test