name: PR Checks

on:
  pull_request:
    branches:
      - master

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}

      - name: Prettify code
        uses: creyD/prettier_action@v3.1
        with:
          prettier_options: --write **/*.{tsx,js,ts,md,css,scss,html,json,yml}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  eslint:
    name: ESLint
    needs: prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install Node.js dependencies
        run: npm install

      - name: Run ESLint
        working-directory: ./src/
        run: npx eslint **/*.{tsx,js,ts} --no-error-on-unmatched-pattern

  build-and-test:
    name: Build and Test
    needs: [prettier, eslint]
    runs-on: ubuntu-latest
    steps:
      - name: Setup kernel for react native, increase watchers
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'


      - name: Install Node.js dependencies
        run: |
          # npm i react-scripts@latest
          # npm install @capacitor/core@latest @capacitor/cli@latest
          npm install -force


      - name: Build
        run: npm run build

      - name: Test
        run: npm run test

  build-apk:
    name: Build Android APK
    needs: [prettier, eslint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Install Capacitor
        run: npm install -g @capacitor/core @ionic/cli@6.20.1

      - name: Install Ionic
        run: npm install -g @ionic/cli

      - name: Install app dependencies
        run: npm install

      - name: Build app
        run: ionic capacitor sync android

      - name: Grant execute permission for gradlew
        working-directory: ./android/
        run: chmod +x gradlew

      - name: Generate the Android APK
        working-directory: ./android/
        run: ./gradlew --no-daemon assembleDebug --info

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v1
        with:
          name: hymnal-app-debug
          path: android/app/build/outputs/apk/debug/app-debug.apk

      - name: Add Comment on PR
        uses: mshick/add-pr-comment@v1
        with:
          message: Android APK for this PR has been built and uploaded. Check Github Actions.
          repo-token: ${{ secrets.GITHUB_TOKEN }}
